# Generated by Django 5.1.6 on 2025-02-27 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="技能名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="技能描述"),
                ),
                (
                    "configuration",
                    models.JSONField(blank=True, default=dict, verbose_name="配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "代理技能",
                "verbose_name_plural": "代理技能",
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="代理名称")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("product_manager", "产品经理"),
                            ("frontend_dev", "前端开发"),
                            ("backend_dev", "后端开发"),
                            ("ux_designer", "用户体验设计师"),
                            ("qa_tester", "测试工程师"),
                            ("data_analyst", "数据分析师"),
                            ("virtual_friend", "虚拟朋友"),
                            ("assistant", "助手"),
                            ("custom", "自定义"),
                        ],
                        default="assistant",
                        max_length=50,
                        verbose_name="代理角色",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="代理描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("busy", "忙碌"),
                            ("disabled", "已禁用"),
                        ],
                        default="offline",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                (
                    "skills",
                    models.JSONField(blank=True, default=dict, verbose_name="技能配置"),
                ),
                (
                    "system_prompt",
                    models.TextField(blank=True, null=True, verbose_name="系统提示"),
                ),
                (
                    "model_config",
                    models.JSONField(blank=True, default=dict, verbose_name="模型配置"),
                ),
                (
                    "api_access",
                    models.JSONField(blank=True, default=dict, verbose_name="API权限"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_agents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI代理",
                "verbose_name_plural": "AI代理",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField(verbose_name="交互内容")),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("message", "消息"),
                            ("command", "命令"),
                            ("response", "响应"),
                            ("task_assignment", "任务分配"),
                            ("status_update", "状态更新"),
                        ],
                        default="message",
                        max_length=20,
                        verbose_name="交互类型",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_interactions",
                        to="agents.agent",
                        verbose_name="发起者",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_interactions",
                        to="agents.agent",
                        verbose_name="接收者",
                    ),
                ),
            ],
            options={
                "verbose_name": "代理交互",
                "verbose_name_plural": "代理交互",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AgentSkillAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_configuration",
                    models.JSONField(blank=True, default=dict, verbose_name="自定义配置"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用状态")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_assignments",
                        to="agents.agent",
                        verbose_name="代理",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_assignments",
                        to="agents.agentskill",
                        verbose_name="技能",
                    ),
                ),
            ],
            options={
                "verbose_name": "代理技能分配",
                "verbose_name_plural": "代理技能分配",
                "unique_together": {("agent", "skill")},
            },
        ),
        migrations.AddField(
            model_name="agentskill",
            name="agents",
            field=models.ManyToManyField(
                related_name="skill_set",
                through="agents.AgentSkillAssignment",
                to="agents.agent",
                verbose_name="拥有此技能的代理",
            ),
        ),
    ]
