# Generated by Django 5.1.6 on 2025-03-03 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentListeningRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="规则描述"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                ("priority", models.IntegerField(default=10, verbose_name="优先级")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("keyword", "关键词匹配"),
                            ("regex", "正则表达式"),
                            ("mention", "提及代理"),
                            ("all_messages", "所有消息"),
                            ("custom", "自定义条件"),
                        ],
                        default="keyword",
                        max_length=20,
                        verbose_name="触发类型",
                    ),
                ),
                (
                    "trigger_condition",
                    models.JSONField(
                        help_text="根据触发类型定义的具体条件，例如关键词列表或正则表达式", verbose_name="触发条件"
                    ),
                ),
                (
                    "listen_in_groups",
                    models.BooleanField(default=True, verbose_name="在群组中监听"),
                ),
                (
                    "listen_in_direct",
                    models.BooleanField(default=True, verbose_name="在直接消息中监听"),
                ),
                (
                    "allowed_groups",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="可以监听的群组ID列表，空表示所有群组",
                        verbose_name="允许的群组",
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("auto_reply", "自动回复"),
                            ("notification", "通知"),
                            ("task", "创建任务"),
                            ("action", "执行动作"),
                            ("custom", "自定义响应"),
                        ],
                        default="auto_reply",
                        max_length=20,
                        verbose_name="响应类型",
                    ),
                ),
                (
                    "response_content",
                    models.JSONField(help_text="根据响应类型定义的具体行为", verbose_name="响应内容"),
                ),
                (
                    "cooldown_period",
                    models.IntegerField(
                        default=0, help_text="规则触发后的冷却时间（秒），0表示无冷却", verbose_name="冷却时间"
                    ),
                ),
                (
                    "last_triggered",
                    models.DateTimeField(blank=True, null=True, verbose_name="最近触发时间"),
                ),
                ("trigger_count", models.IntegerField(default=0, verbose_name="触发次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listening_rules",
                        to="agents.agent",
                        verbose_name="代理",
                    ),
                ),
            ],
            options={
                "verbose_name": "代理监听规则",
                "verbose_name_plural": "代理监听规则",
                "ordering": ["priority", "-updated_at"],
            },
        ),
    ]
