# Generated by Django 5.1.6 on 2025-03-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_agentlisteningrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentlisteningrule",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("keyword", "关键词匹配"),
                    ("regex", "正则表达式"),
                    ("mention", "提及代理"),
                    ("all_messages", "所有消息"),
                    ("sentiment", "情绪分析"),
                    ("context_aware", "上下文感知"),
                    ("custom", "自定义条件"),
                ],
                default="keyword",
                max_length=20,
                verbose_name="触发类型",
            ),
        ),
    ]
