# Generated by Django 5.1.6 on 2025-03-25 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0003_alter_agentlisteningrule_trigger_type"),
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="名称"),
                ),
                (
                    "color",
                    models.CharField(default="blue", max_length=20, verbose_name="颜色"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
            ],
            options={
                "verbose_name": "任务标签",
                "verbose_name_plural": "任务标签",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("in_progress", "进行中"),
                            ("review", "审核中"),
                            ("completed", "已完成"),
                            ("blocked", "已阻塞"),
                            ("canceled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("development", "开发"),
                            ("design", "设计"),
                            ("research", "研究"),
                            ("writing", "写作"),
                            ("analysis", "分析"),
                            ("planning", "规划"),
                            ("testing", "测试"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "due_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="截止日期"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度百分比")),
                (
                    "estimated_hours",
                    models.FloatField(blank=True, null=True, verbose_name="预计耗时(小时)"),
                ),
                (
                    "actual_hours",
                    models.FloatField(blank=True, null=True, verbose_name="实际耗时(小时)"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="是否重复任务"),
                ),
                (
                    "recurrence_pattern",
                    models.JSONField(blank=True, null=True, verbose_name="重复模式"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="groups.group",
                        verbose_name="关联群组",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="task_management.task",
                        verbose_name="父任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "is_system_comment",
                    models.BooleanField(default=False, verbose_name="是否系统评论"),
                ),
                (
                    "is_status_update",
                    models.BooleanField(default=False, verbose_name="是否状态更新"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_by_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_comments",
                        to="agents.agent",
                        verbose_name="创建代理",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建用户",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="task_management.task",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务评论",
                "verbose_name_plural": "任务评论",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="是否主要负责人"),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=100, verbose_name="角色"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_assignments",
                        to="agents.agent",
                        verbose_name="分配代理",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分配者",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分配用户",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="task_management.task",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务分配",
                "verbose_name_plural": "任务分配",
                "unique_together": {
                    ("task", "assigned_agent"),
                    ("task", "assigned_user"),
                },
            },
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_dependencies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "dependent_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="task_management.task",
                        verbose_name="依赖任务",
                    ),
                ),
                (
                    "prerequisite_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="task_management.task",
                        verbose_name="前置任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务依赖",
                "verbose_name_plural": "任务依赖",
                "unique_together": {("dependent_task", "prerequisite_task")},
            },
        ),
        migrations.CreateModel(
            name="TaskTagAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分配者",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="task_management.tasktag",
                        verbose_name="标签",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_assignments",
                        to="task_management.task",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务标签分配",
                "verbose_name_plural": "任务标签分配",
                "unique_together": {("task", "tag")},
            },
        ),
    ]
