# Generated by Django 5.1.6 on 2025-02-28 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="群组名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="群组描述"),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="group_avatars/",
                        verbose_name="群组头像",
                    ),
                ),
                (
                    "group_settings",
                    models.JSONField(blank=True, default=dict, verbose_name="群组设置"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "群组",
                "verbose_name_plural": "群组",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("human", "人类"), ("agent", "AI代理"), ("system", "系统")],
                        default="human",
                        max_length=10,
                        verbose_name="发送者类型",
                    ),
                ),
                ("content", models.JSONField(verbose_name="消息内容")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("image", "图片"),
                            ("file", "文件"),
                            ("task", "任务"),
                            ("system", "系统消息"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="groups.group",
                        verbose_name="群组",
                    ),
                ),
                (
                    "mentioned_agents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mentioned_in_messages",
                        to="agents.agent",
                        verbose_name="提及代理",
                    ),
                ),
                (
                    "mentioned_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mentioned_in_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提及用户",
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="groups.groupmessage",
                        verbose_name="回复消息",
                    ),
                ),
                (
                    "sender_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_group_messages",
                        to="agents.agent",
                        verbose_name="发送代理",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_group_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "群组消息",
                "verbose_name_plural": "群组消息",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GroupRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="规则描述"),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("trigger", "触发条件"),
                            ("response", "回应规则"),
                            ("schedule", "定时任务"),
                            ("system", "系统规则"),
                        ],
                        default="trigger",
                        max_length=20,
                        verbose_name="规则类型",
                    ),
                ),
                ("condition", models.JSONField(verbose_name="触发条件")),
                ("action", models.JSONField(verbose_name="执行动作")),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="groups.group",
                        verbose_name="群组",
                    ),
                ),
                (
                    "target_agents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="group_rules",
                        to="agents.agent",
                        verbose_name="目标代理",
                    ),
                ),
            ],
            options={
                "verbose_name": "群组规则",
                "verbose_name_plural": "群组规则",
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[("human", "人类"), ("agent", "AI代理")],
                        default="human",
                        max_length=10,
                        verbose_name="成员类型",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "成员"),
                            ("admin", "管理员"),
                            ("observer", "观察者"),
                        ],
                        default="member",
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "member_settings",
                    models.JSONField(blank=True, default=dict, verbose_name="成员设置"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="agents.agent",
                        verbose_name="代理",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="groups.group",
                        verbose_name="群组",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "群组成员",
                "verbose_name_plural": "群组成员",
                "ordering": ["joined_at"],
                "unique_together": {("group", "agent"), ("group", "user")},
            },
        ),
    ]
